### ISSUE TITLE
Crash on register

### ISSUE THREAD

**Issue by MrMargouillat** [carat-project/carat-android#49]
Hi, 
I've spotted this exception while translation the app to French.
It appears that the app launches perfectly the first time and runs as exptected then after a restart it runs direcly into this error.
I'll trying to learn more about it.
There is the logcat:

`10-31 09:09:24.740 27633-27703/edu.berkeley.cs.amplab.carat.android E/AndroidRuntime: FATAL EXCEPTION: Thread-7
                                                                                      Process: edu.berkeley.cs.amplab.carat.android, PID: 27633
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void edu.berkeley.cs.amplab.carat.thrift.CaratService$Client.registerMe(edu.berkeley.cs.amplab.carat.thrift.Registration)' on a null object reference
                                                                                          at edu.berkeley.cs.amplab.carat.android.protocol.CommunicationManager.registerMe(CommunicationManager.java:104)
                                                                                          at edu.berkeley.cs.amplab.carat.android.protocol.CommunicationManager.registerOnFirstRun(CommunicationManager.java:189)
                                                                                          at edu.berkeley.cs.amplab.carat.android.protocol.CommunicationManager.uploadSamples(CommunicationManager.java:119)
                                                                                          at edu.berkeley.cs.amplab.carat.android.protocol.SampleSender.sendSamples(SampleSender.java:52)
                                                                                          at edu.berkeley.cs.amplab.carat.android.CaratApplication.checkAndSendSamples(CaratApplication.java:611)
                                                                                          at edu.berkeley.cs.amplab.carat.android.MainActivity$3.run(MainActivity.java:255)
                                                                                          at java.lang.Thread.run(Thread.java:761)`

**Comment by MrMargouillat** [comment]
I've done some test and it seems like it has to do with the translation... Since it happends only one my fork...
But when I import my string file into a copy directly from master the problem disappears... And this is the only file modified on my fork.... Really weird...
Also when I launch the app the error is logged but doesn't cause the app to crash... I really don't understand...

**Comment by MrMargouillat** [comment]
After other tests it seems like it's not due completely to the translation.
After that I left the app doing nothing, my phone locked and when I came back and unlocked, the issue appeared again, even without the translation.
(I hope this is helpful ;) )

**Comment by lagerspetz** [comment]
Do you get this issue with Carat from Google Play or the latest release: https://github.com/carat-project/carat-android/releases/tag/v2.17.9 The issue may be related to a trust store we use.

**Comment by MrMargouillat** [comment]
Hi, I've done the same tests, and no I don't have any the bug on the Google Play one.

**Comment by Raffaele74** [comment]
I've setted "wifi only".
Carat, if there is no wifi, it takes a long time (a few dozen seconds) to look for wifi.
After that, the application shows a message "set wifi on or cancel" (but wifi is on, there is no one).
An unusual behavior, but not a bug. However in this screen of dozen seconds is white.
Could this be?

**Comment by lagerspetz** [comment]
There were communication issues with this version as well, so I have gone back to the old method. A new update is on Google Play for this. It should be faster, but it is something we need to replace soon.
